# Generated by Django 4.0.2 on 2022-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_expense_description_expense_image_expense_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
